name: muslim
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.18.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  toggle_switch: ^2.0.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  flutter_bloc: ^8.1.2
  shared_preferences: ^2.1.0
  flutter_native_splash: ^2.2.16
  get_it: ^7.3.0
  audioplayers: ^4.0.1
  easy_debounce: ^2.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.0
  flutter_launcher_icons: "^0.13.1"
flutter_native_splash:
  color: "#F8F8F8"
  image: assets/image/muslim.png
  android: true
  ios: true
flutter_icons:
  android: "launcher_icon"
  image_path: "assets/image/muslim.png"
  ios: true
  remove_alpha_ios: true
flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/data/
    - assets/sound/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/font/Montserrat-Regular.ttf
        - asset: assets/font/Montserrat-Italic.ttf
          style: italic
        - asset: assets/font/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/font/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/font/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/font/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/font/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/font/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Arabic
      fonts:
        - asset: assets/font/qalam.ttf
